### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by firaschmek** [eggerdo/ZmqVideoChat#3]
I followed the steps in the description of the project but I get this error any help please. 
Error: Could not locate the bindings file. Tried:
 → /home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/zmq/build/zmq.node
 → /home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/zmq/build/Debug/zmq.node
 → /home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/zmq/build/Release/zmq.node
 → /home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/zmq/out/Debug/zmq.node
 → /home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/zmq/Debug/zmq.node
 → /home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/zmq/out/Release/zmq.node
 → /home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/zmq/Release/zmq.node
 → /home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/zmq/build/default/zmq.node
 → /home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/zmq/compiled/5.6.0/linux/x64/zmq.node
    at bindings (/home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/zmq/lib/index.js:6:30)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/firas/Desktop/PFE/ZmqVideoChat-master/server/videochat.node/node_modules/zmq/index.js:2:18)
    at Module._compile (module.js:413:34)

**Comment by eggerdo** [comment]
Hey, I'm afraid this error comes from the zmq node module that I am using in nodejs. So nothing I have any influence on nor any idea how to solve. But have a look at this [issue](https://github.com/JustinTulloss/zeromq.node/issues/369) which sounds pretty much the same as your error, so maybe it helps.
